import { FormEvent, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import services from '@/services';
import Notice from '@/components/Notification';

export default function LoginPage() {

  const router = useRouter();

  useEffect(() => {
    if (router.query.r) {
      Notice.error({
        title: '登录失败',
        description: '用户名与密码不匹配。',
      });
      router.replace('/account/login')
    }
  }, [router]);

  /** 提交登录 */
  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const email = e.currentTarget['email'].value;
    const password = e.currentTarget['password'].value;

    services.login({ email, password }).then(res => {
      localStorage.setItem('LINE_USER', JSON.stringify(res.user));
      router.push('/');
    });
  }

  return (
    <>
      <Head>
        <title>登录 | Line</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-wrap items-center justify-center w-full h-screen">
        <div className="flex flex-col w-full p-8 bg-gray-100 rounded-lg lg:w-2/6 md:w-1/2">
          <form onSubmit={handleSubmit}>
            <h2 className="mb-5 text-lg font-medium text-gray-900 title-font">登录</h2>
            <div className="relative mb-4">
              <label htmlFor="email" className="text-sm leading-7 text-gray-600">电子邮箱</label>
              <input
                type="email"
                id="email"
                name="email"
                className="w-full px-3 py-1 text-base leading-8 text-gray-700 transition-colors duration-200 ease-in-out bg-white border border-gray-300 rounded outline-none focus:border-green-600"
              />
            </div>
            <div className="relative mb-4">
              <label htmlFor="password" className="text-sm leading-7 text-gray-600">密码</label>
              <input
                type="password"
                id="password"
                name="password"
                className="w-full px-3 py-1 text-base leading-8 text-gray-700 transition-colors duration-200 ease-in-out bg-white border border-gray-300 rounded outline-none focus:border-green-600"
              />
            </div>
            <button type="submit" className="px-8 py-2 text-lg text-white bg-green-600 border-0 rounded focus:outline-none hover:bg-green-700">登录</button>
            <p className="mt-3 text-xs text-gray-500">还没有账户？<Link href="/account/sign-in" className='text-base text-green-600'>前往注册</Link></p>
          </form>
        </div>
      </section>
    </>
  )
}
